import React from 'react'

const tsunami = () => {
  return (
    <div>
         <div class="view-content">
          <div class="views-row"><h1 class="views-field views-field-title page-title"><span class="field-content">Tsunami</span></h1><div class="views-field views-field-body"><div class="field-content">

<p><img alt="Tsunami" data-entity-type="file" data-entity-uuid="571b4d45-4cf5-44a3-bcf2-7c8aab8e74e1" src="/sites/default/files/inline-images/Tsunami_0.png" class="align-right" />The Earth's lithosphere is broken up into a bunch of discrete pieces, called plates that move around the surface of the planet. There are seven or eight major plates (depending on how they are defined) and many minor plates.  This motion is driven by the flow of the mantle rock beneath the plates and by the forces plates exert at their boundaries where they touch each other.  Earthquakes happen when plates move with respect to each other because of the friction and stress at the edges of plates prevents them from slipping smoothly at their boundaries. <strong>When one plate is forced to dive beneath another plate, there is no way to do it except with some component of vertical motion creating tsunami (please see figure) </strong><strong>.</strong><strong> </strong></p>



<p>The tsunami that occurred during 2004 Sumatra-Andaman earthquake of Mw 9.3 was primarily caused by vertical displacement of the seafloor, in response to slip on the inter-plate thrust fault.  The earthquake and resulting tsunami in the Indian Ocean affected many countries in Southeast Asia and beyond, including Indonesia, Sri Lanka, India, Thailand, the Maldives, Somalia, Myanmar, Malaysia, Seychelles and others. Many other countries, especially Australia and those in Europe incurred casualties due to the tsunami, because they had large numbers of citizens traveling in the region on holiday. This tsunami-genic earthquake was one of the ten worst earthquakes in recorded history, as well as the single worst tsunami in history. Indonesia was the worst affected country. Beyond the heavy toll on human lives, the Indian Ocean earthquake has caused an enormous environmental impact that will affect the region for many years to come. The disaster also caused a substantial geo-physical impact in Indian Ocean. The disaster invited attention of affected countries for setting up effective tsunami early warning system and institutional mechanism for handling disasters.</p>

<p>The Government of India has put in place an Early Warning System for mitigation of such oceanogenic disasters under the control of Indian National Center for Ocean Information Services (INCOIS), Hyderabad. A state-of-the-art early warning centre was established with the necessary computational and communication infrastructure that enables reception of real-time data from  sensors, analysis of the data, generation and dissemination of tsunami advisories following a standard operating procedure. Seismic and sea-level data are continuously monitored in the Early Warning Centre using custom-built software application that generates alarms/alerts in the warning centre whenever a pre-set threshold is crossed. Tsunami warnings/watches are then generated based on pre-set decision support rules and disseminated to the concerned authorities for action, as per pre-decided standard operating procedure. The efficiency of this end-to-end system was proved during the large under-sea earthquake of 8.4 M that occurred on September 12, 2007 in the Indian Ocean.</p>

<p><strong>The 2004 tsunami also prompted NDMA to formulate Tsunami Risk Management Guidelines to outline inter-agency roles and responsibilities, tsunami risk preparedness, mitigation and response</strong>.  </p>

<p>The Guidelines recommends practical and effective ways for awareness generation, capacity building, education, training and research &amp; development for better tsunami risk management.  The Guidelines explore options for effective dissemination of tsunami alert and warning messages generated by INCOIS to the concerned agencies and coastal vulnerable communities exposed to tsunamis in a coordinated manner.</p>

<p>Structural Mitigation measures, as envisaged in the Guidelines, gives a brief guidance on design and construction of new structures as well as strategies for protecting lifeline and priority structures from Tsunamis along the seafront. The Guidelines urge BIS to roll out the pending construction standards entitled ‘Criteria for Tsunami-Resistant Design of Structures’. It further recommends a robust techno-legal regime through efficient land use practices, bioshields, shelter belt plantation and mangrove regeneration with community involvement. A strong mechanism has been recommended for effective emergency response by involving local police network, civil defence volunteers wherever available, home guards, State Disaster Response Forces and National Disaster Response Force. Further, the Guidelines explore the  provisions of Disaster Management Act 2005 to mainstream concern of Tsunami risk management in disaster management plans of various levels. </p>



<p><img alt="zone map" data-entity-type="file" data-entity-uuid="583c0861-a3bb-483c-b4ac-0de298471613" src="/sites/default/files/inline-images/zoneMap_0.png" /></p>

<p><strong>Recover and build</strong></p>

<ul><li>You should continue using a Weather Radio or staying tuned to a Coast Guard emergency frequency station or a local radio or television station for updated emergency information.</li>
	<li>Check yourself for injuries and get first aid if necessary before helping injured or trapped persons.</li>
	<li>If someone needs to be rescued, call professionals with the right equipment to help Many people have been killed or injured trying to rescue others in flooded areas.</li>
	<li>Help people who require special assistance—Infants, elderly people, those without transportation, large families who may need additional help in an emergency situation, people with disabilities, and the people who care for them.</li>
	<li>Avoid disaster areas. Your presence might hamper rescue and other emergency operations and put you at further risk from the residual effects of floods, such as contaminated water, crumbled roads, landslides, mudflows, and other hazards.</li>
	<li>Use the telephone only for emergency calls.Telephone lines are frequently overwhelmed in disaster situations. They need to be clear for emergency calls to get through.</li>
	<li>Stay out of a building if water remains around it. Tsunami water, like floodwater, can undermine foundations, causing buildings to sink, floors to crack, or walls to collapse.</li>
	<li>When re-entering buildings or homes, use extreme caution. Tsunami-driven floodwater may have damaged buildings where you least expect it. Carefully watch every step you take.</li>
	<li>Wear long pants, a long-sleeved shirt, and sturdy shoes. The most common injury following a disaster is cut feet.</li>
	<li>Use battery-powered lanterns or flashlights when examining buildings. Battery-powered lighting is the safest and easiest to use, and it does not present a fire hazard for the user, occupants, or building. DO NOT USE CANDLES.</li>
	<li>Examine walls, floors, doors, staircases, and windows to make sure that the building is not in danger of collapsing.</li>
	<li>Inspect foundations for cracks or other damage. Cracks and damage to a foundation can render a building uninhabitable.</li>
	<li>Look for fire hazards. Under the earthquake action there may be broken or leaking gas lines, and under the tsunami flooded electrical circuits, or submerged furnaces or electrical appliances. Flammable or explosive materials may have come from upstream. Fire is the most frequent hazard following floods.</li>
	<li>Check for gas leaks. If you smell gas or hear a blowing or hissing noise, open a window and get everyone outside quickly. Turn off the gas using the outside main valve if you can, and call the gas company from a neighbour’s home. If you turn off the gas for any reason, it must be turned back on by a professional.</li>
	<li>Look for electrical system damage. If you see sparks or broken or frayed wires, or if you smell burning insulation, turn off the electricity at the main fuse box or circuit breaker. If you have to step in water to get to the fuse box or circuit breaker, call an electrician first for advice. Electrical equipment should be checked and dried before being returned to service</li>
	<li>Check for damage to sewage and water lines.If you suspect sewage lines are damaged under the quake, avoid using the toilets and call a plumber. If water pipes are damaged, contact the water company and avoid using water from the tap. You can obtain safe water from undamaged water heaters or by melting ice cubes that were made before the tsunami hit. Turn off the main water valve before draining water from these sources. Use tap water only if local health officials advise it is safe.</li>
	<li>Watch out for wild animals, especially poisonous snakes that may have come into buildings with the water. Use a stick to poke through debris. Tsunami floodwater flushes snakes and animals out of their homes.</li>
	<li>Watch for loose plaster, drywall, and ceilings that could fall.</li>
	<li>Take pictures of the damage, both of the building and its contents, for insurance claims. Open the windows and doors to help dry the building.</li>
	<li>Shovel mud before it solidifies.</li>
	<li>Check food supplies.Any food that has come in contact with floodwater may be contaminated and should be thrown out.</li>
	<li>Expect aftershocks. If the earthquake is of large magnitude (magnitude 8 to 9+ on the Richter scale) and located nearby, some aftershocks could be as large as magnitude 7+ and capable of generating another tsunami. The number of aftershocks will decrease over the course of several days, weeks, or months depending on how large the main shock was.</li>
	<li>Watch your animals closely.</li>
	<li>Keep all your animals under your direct control.</li>
</ul></div></div><div class="views-field views-field-field-image"><div class="field-content"></div></div></div>

    </div>
    <div class="view-content">
          <div class="views-row"><h1 class="views-field views-field-title page-title"><span class="field-content">Tsunami: Do’s &amp; Don’ts </span></h1><div class="views-field views-field-body"><div class="field-content"><ul><li>You should find out if your home, school, workplace, or other frequently visited locations are in tsunami hazard areas along sea-shore.</li>
	<li>Know the height of your street above sea level and the distance of your street from the coast or other high-risk waters. (Local administration may put sign boards).</li>
	<li>Plan evacuation routes from your home, school, workplace, or any other place you could be where tsunamis present a risk.</li>
	<li>If your children's school is in an identified inundation zone, find out what the school evacuation plan is.</li>
	<li>Practice your evacuation routes.</li>
	<li>Use a Weather Radio or stay tuned to a local radio or television station to keep informed of local watches and warnings.</li>
	<li>Talk to your insurance agent.Homeowners' policies may not cover flooding from a tsunami. Ask the Insurance Agent about the benefits from Multi-Hazard Insurance Schemes.</li>
	<li>Discuss tsunamis with your family.Everyone should know what to do in a tsunami situation. Discussing tsunamis ahead of time will help reduce fear and save precious time in an emergency. Review flood safety and preparedness measures with your family.</li>
</ul><p><strong>If you are in an area at risk from tsunamis</strong></p>

<ul><li>You should find out if your home, school, workplace, or other frequently visited locations are in tsunami hazard areas.</li>
	<li>Know the height of your street above sea level and the distance of your street from the coast or other high-risk waters. (Local administration may put sign boards). Also find out the height above sea level and the distance from the coast of outbuildings that house animals, as well as pastures or corrals.</li>
	<li>Plan evacuation routes from your home, school, workplace, or any other place you could be where tsunamis present a risk. If possible, pick areas (30 meters) above sea level or go as far as 3 kilometres inland, away from the coastline. If you cannot get this high or far, go as high or far as you can. Every meter inland or upward may make a difference. You should be able to reach your safe location on foot within 15 minutes. After a disaster, roads may become blocked or unusable. Be prepared to evacuate by foot if necessary. Footpaths normally lead uphill and inland, while many roads parallel coastlines. Follow posted tsunami evacuation routes; these will lead to safety. Local emergency management officials can advise you on the best route to safety and likely shelter locations.</li>
	<li>If your children's school is in an identified inundation zone, find out what the school evacuation plan is. Find out if the plan requires you to pick your children up from school or from another location. Telephone lines during a tsunami watch or warning may be overloaded and routes to and from schools may be jammed.</li>
	<li>Practice your evacuation routes. Familiarity may save your life. Be able to follow your escape route at night and during inclement weather. Practicing your plan makes the appropriate response more of a reaction, requiring less thinking during an actual emergency situation.</li>
	<li>Use a Weather Radio or stay tuned to a local radio or television station to keep informed of local watches and warnings.</li>
	<li>Talk to your insurance agent.Homeowners' policies may not cover flooding from a tsunami. Ask the Insurance Agent about the benefits from Multi-Hazard Insurance Schemes.</li>
	<li>Discuss tsunamis with your family. Everyone should know what to do in a tsunami situation. Discussing tsunamis ahead of time will help reduce fear and save precious time in an emergency. Review flood safety and preparedness measures with your family.</li>
</ul><p><strong>If you are visiting an area at risk from tsunamis</strong></p>

<ul><li>Check with the hotel or campground operators for tsunami evacuation information and find out what the warning system is for tsunamis. It is important to know designated escape routes before a warning is issued.</li>
	<li>One of the early warning signals of a tsunami is that the sea water recedes several metres, exposing fish on shallow waters or on the beaches. If you see the sea water receding, you must immediately leave the beach and go to higher ground far away from the beach.</li>
	<li>Protect Your Property</li>
	<li>You should avoid building or living in buildings within 200 meters of the high tide coastline.</li>
	<li>These areas are more likely to experience damage from tsunamis, strong winds, or coastal storms.</li>
	<li>Make a list of items to bring inside in the event of a tsunami.</li>
	<li>A list will help you remember anything that can be swept away by tsunami water.</li>
	<li>Elevate coastal homes.</li>
	<li>Most tsunami waves are less than 3 meters. Elevating your house will help reduce damage to your property from most tsunamis.</li>
	<li>Take precautions to prevent flooding.</li>
	<li>Have an engineer check your home and advise about ways to make it more resistant to tsunami water.</li>
	<li>There may be ways to divert waves away from your property. Improperly built walls could make your situation worse. Consult with a professional for advice.</li>
	<li>Ensure that any outbuildings, pastures, or corrals are protected in the same way as your home. When installing or changing fence lines, consider placing them in such a way that your animals are able to move to higher ground in the event of a tsunami.</li>
</ul><h3><strong>What to Do if You Feel a Strong Coastal Earthquake</strong></h3>

<p><strong>If you feel an earthquake that lasts 20 seconds or longer when you are in a coastal area, you should:</strong></p>

<ul><li>Drop, cover, and hold on. You should first protect yourself from the earthquake damages.</li>
</ul><p><strong>When the shaking stops:</strong></p>

<ul><li>Gather members of your household and move quickly to higher ground away from the coast. A tsunami may be coming within minutes.</li>
</ul><p>Avoid downed power lines and stay away from damaged buildings and bridges from which Heavy objects might fall during an aftershock.</p>

<p><strong>If you are on land</strong></p>

<ul><li>Be aware of tsunami facts. This knowledge could save your life! Share this knowledge with your relatives and friends. It could save their lives!</li>
</ul><p><strong>If you are in school and you hear there is a tsunami warning:</strong></p>

<ul><li>You should follow the advice of teachers and other school personnel.</li>
</ul><p><strong>If you are at home and hear there is a tsunami warning:</strong></p>

<ul><li>You should make sure your entire family is aware of the warning. Your family should evacuate your house if you live in a tsunami evacuation zone. Move in an orderly, calm and safe manner to the evacuation site or to any safe place outside your evacuation zone. Follow the advice of local emergency and law enforcement authorities.</li>
</ul><p><strong>If you are at the beach or near the ocean and you feel the earth shake:</strong></p>

<ul><li>Move immediately to higher ground, DO NOT wait for a tsunami warning to be announced. Stay away from rivers and streams that lead to the ocean as you would stay away from the beach and ocean if there is a tsunami. A regional tsunami from a local earthquake could strike some areas before a tsunami warning could be announced.</li>
	<li>Tsunamis generated in distant locations will generally give people enough time to move to higher ground. For locally-generated tsunamis, where you might feel the ground shake, you may only have a few minutes to move to higher ground.</li>
	<li>High, multi-storied, reinforced concrete hotels are located in many low-lying coastal areas. The upper floors of these hotels can provide a safe place to find refuge should there be a tsunami warning and you cannot move quickly inland to higher ground.</li>
	<li>Homes and small buildings located in low-lying coastal areas are not designed to withstand tsunami impacts. Do not stay in these structures should there be a tsunami warning.</li>
	<li>Offshore reefs and shallow areas may help break the force of tsunami waves, but large and dangerous wave can still be a threat to coastal residents in these areas.</li>
	<li>Staying away from all low-lying areas is the safest advice when there is a tsunami warning.</li>
</ul><p><strong>If you are on a boat:</strong></p>

<ul><li>Since tsunami wave activity is imperceptible in the open ocean, do not return to port if you are at sea and a tsunami warning has been issued for your area. Tsunamis can cause rapid changes in water level and unpredictable dangerous currents in harbours and ports.</li>
</ul><p><strong>If there is time to move your boat or ship from port to deep water (after a tsunami warning has been issued), you should weigh the following considerations:</strong></p>

<ul><li>Most large harbours and ports are under the control of a harbor authority and/or a vessel traffic system. These authorities direct operations during periods of increased readiness (should a tsunami be expected), including the forced movement of vessels if deemed necessary. Keep in contact with the authorities should a forced movement of vessel be directed.</li>
	<li>Smaller ports may not be under the control of a harbor authority. If you are aware there is a tsunami warning and you have time to move your vessel to deep water, then you may want to do so in an orderly manner, in consideration of other vessels.</li>
	<li>Owners of small boats may find it safest to leave their boat at the pier and physically move to higher ground, particularly in the event of a locally-generated tsunami.</li>
	<li>Concurrent severe weather conditions (rough seas outside of safe harbor) could present a greater hazardous situation to small boats, so physically moving yourself to higher ground may be the only option.</li>
	<li>Damaging wave activity and unpredictable currents can affect harbours for a period of time following the initial tsunami impact on the coast. Contact the harbor authority before returning to port making sure to verify that conditions in the harbor are safe for navigation and berthing.</li>
</ul><p><strong>What to do after a Tsunami</strong></p>

<ul><li>You should continue using a Weather Radio or staying tuned to a Coast Guard emergency frequency station or a local radio or television station for updated emergency information.</li>
	<li>The Tsunami may have damaged roads, bridges, or other places that may be unsafe.</li>
	<li>Check yourself for injuries and get first aid if necessary before helping injured or trapped persons.</li>
	<li>If someone needs to be rescued, call professionals with the right equipment to help.</li>
	<li>Help people who require special assistance— Infants, elderly people, those without transportation, large families who may need additional help in an emergency situation, people with disabilities, and the people who care for them.</li>
	<li>Avoid disaster areas.</li>
	<li>Your presence might hamper rescue and other emergency operations and put you at further risk from the residual effects of floods, such as contaminated water, crumbled roads, landslides, mudflows, and other hazards.</li>
	<li>Use the telephone only for emergency calls.Telephone lines are frequently overwhelmed in disaster situations. They need to be clear for emergency calls to get through.</li>
	<li>Stay out of a building if water remains around it.Tsunami water, like floodwater, can undermine foundations, causing buildings to sink, floors to crack, or walls to collapse.</li>
	<li>When re-entering buildings or homes, use extreme caution.Tsunami-driven floodwater may have damaged buildings where you least expect it. Carefully watch every step you take.</li>
	<li>Wear long pants, a long-sleeved shirt, and sturdy shoes.The most common injury following a disaster is cut feet.</li>
	<li>Use battery-powered lanterns or flashlights when examining buildings.Battery-powered lighting is the safest and easiest to use, and it does not present a fire hazard for the user, occupants, or building. DO NOT USE CANDLES.</li>
	<li>Examine walls, floors, doors, staircases, and windows to make sure that the building is not in danger of collapsing. Inspect foundations for cracks or other damage. Cracks and damage to a foundation can render a building uninhabitable.</li>
	<li>Look for fire hazards.Under the earthquake action there may be broken or leaking gas lines, and under the tsunami flooded electrical circuits, or submerged furnaces or electrical appliances. Flammable or explosive materials may have come from upstream. Fire is the most frequent hazard following floods.</li>
	<li>Check for gas leaks.If you smell gas or hear a blowing or hissing noise, open a window and get everyone outside quickly. Turn off the gas using the outside main valve if you can, and call the gas company from a neighbour’s home. If you turn off the gas for any reason, it must be turned back on by a professional.</li>
	<li>Look for electrical system damage. If you see sparks or broken or frayed wires, or if you smell burning insulation, turn off the electricity at the main fuse box or circuit breaker. If you have to step in water to get to the fuse box or circuit breaker, call an electrician first for advice. Electrical equipment should be checked and dried before being returned to service.\CCheck for damage to sewage and water lines. If you suspect sewage lines are damaged under the quake, avoid using the toilets and call a plumber. If water pipes are damaged, contact the water company and avoid using water from the tap. You can obtain safe water from undamaged water heaters or by melting ice cubes that were made before the tsunami hit. Turn off the main water valve before draining water from these sources. Use tap water only if local health officials advise it is safe.</li>
	<li>Watch out for wild animals, especially poisonous snakes that may have come into buildings with the water. Use a stick to poke through debris. Tsunami floodwater flushes snakes and animals out of their homes.</li>
	<li>Watch for loose plaster, drywall, and ceilings that could fall.</li>
	<li>Take pictures of the damage, both of the building and its contents, for insurance claims. Open the windows and doors to help dry the building.</li>
	<li>Shovel mud before it solidifies.</li>
	<li>Check food supplies.</li>
	<li>Any food that has come in contact with floodwater may be contaminated and should be thrown out.</li>
	<li>Expect aftershocks. If the earthquake is of large magnitude (magnitude 8 to 9+ on the Richter scale) and located nearby, some aftershocks could be as large as magnitude 7+ and capable of generating another tsunami. The number of aftershocks will decrease over the course of several days, weeks, or months depending on how large the main shock was.</li>
	<li>Watch your animals closely. Keep all your animals under your direct control. Hazardous materials abound in flooded areas. Your pets may be able to escape from your home or through a broken fence. Pets may become disoriented, particularly because flooding usually affects scent markers that normally allow them to find their homes. The behaviour of pets may change dramatically after any disruption, becoming aggressive or defensive, so be aware of their well-being and take measures to protect them from hazards, including displaced wild animals, and to ensure the safety of other people and animals.</li>
</ul></div></div><div class="views-field views-field-field-image"><div class="field-content"></div></div></div>

    </div>
  
      
          </div>


  )
}

export default tsunami